### ISSUE TITLE
in newest versions above ground floods are broken

### ISSUE THREAD

**Issue by Slydylan** [jake-white/OopsAllFlooded#1]
on vow and offense i've seen it that the above ground floods no longer work
such that the flood stage is permanently stuck below ground, but the facility flood level works fine
also if it is not too much cost on performance having the underground flood stage stretch wider for potentially larger dungeon gens on rend and dine would be preferable as i have seen dungen go past the radius of the water especially with SCPBDungen

**Comment by jake-white** [comment]
Yeah I've noticed the above ground issue, I think I know what's causing it so should be fixed soon. I'll look into the sizing haven't extensively tested on the high level moons yet.
